### ISSUE TITLE
rbo != RBO in prefixes

### ISSUE THREAD

**Issue by jamesamcl** [marvinm2/AOPWikiRDF#22] opened 2024-08-20 18:30 UTC
The prefix:

    @prefix rbo: <http://purl.obolibrary.org/obo/RBO_>.

Does not match its usage:

        go:0008150      RBO:00015021 ;
        pato:0000001    "WIKI:1" ;

as prefixes are case sensitive in Turtle, see https://www.w3.org/TR/turtle/

> Turtle's @prefix and @base declarations are case sensitive, the SPARQL dervied PREFIX and BASE are case insensitive.

**Comment by marvinm2** [comment] 2024-08-20 19:11
Thank you. Indeed, this issue was spotted. Today I started implementing quality control GH action, which indicated the prefix (this is new in AOP-Wiki). See https://github.com/marvinm2/AOPWikiRDF/issues/20

I will close this as soon as it is resolved. Thank you for your feedback!

**Comment by marvinm2** [comment] 2024-08-20 20:06
The issue is resolved, and a GH action is in place to identify Turtle syntax errors. The newly generated RDF is valid: https://github.com/marvinm2/AOPWikiRDF/actions/runs/10478314279

**Closed by marvinm2** 2024-08-20 20:06 UTC
